version: '3.3'
services:
  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php7-3
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8000:80
    networks:
      - default

  db:
    container_name: mysql8
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourroot
      MYSQL_DATABASE: yourdb
      MYSQL_USER: youruser
      MYSQL_PASSWORD: yourpassword
    ports:
      - 6033:3306
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8001:80
    environment:
      MYSQL_USER: youruser
      MYSQL_PASSWORD: yourpassword
      MYSQL_ROOT_PASSWORD: yourroot
    depends_on:
      - db
  
volumes:
  persistent:
